global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
  - job_name: 'ml_service'
    static_configs:
      - targets: ['ml_service:5000'] 