"""Add tone field to Post

Revision ID: 07def778fc14
Revises: 1d573e5c27e1
Create Date: 2025-07-09 12:37:17.428376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07def778fc14'
down_revision: Union[str, Sequence[str], None] = '1d573e5c27e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tone', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'tone')
    # ### end Alembic commands ###
