name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v3

      - name: Build and start containers
        run: |
          docker compose build
          docker compose up -d

      - name: Wait for Postgres to be healthy
        run: |
          until docker compose exec -T db pg_isready -U user; do sleep 2; done

      - name: Run backend tests inside container
        run: |
          docker compose exec -T backend pytest

      - name: Run ML service tests inside container
        run: |
          docker compose exec -T ml_service pytest || true

      - name: Lint backend (inside container)
        run: |
          docker compose exec -T backend flake8 .

      - name: Lint ML service (inside container)
        run: |
          docker compose exec -T ml_service flake8 . || true

      - name: Stop and clean up containers
        if: always()
        run: docker compose down -v
