name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: socialmedia
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build Docker images
        run: docker compose build

      - name: Install common dev tools
        run: pip install flake8 pytest

      # Backend tests and lint
      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run backend tests
        env:
          DATABASE_URL: postgresql://user:password@db:5432/socialmedia
        run: |
          cd backend
          pytest

      - name: Lint backend
        run: |
          cd backend
          flake8 .

      # ML service
      - name: Install ML service dependencies
        run: |
          cd ml_service
          pip install -r requirements.txt

      - name: Run ML service tests
        run: |
          cd ml_service
          if [ -d tests ]; then pytest || exit 1; fi

      - name: Lint ML service
        run: |
          cd ml_service
          flake8 .
